#ifndef PRINTROUNDS_H
#define PRINTROUNDS_H

#include <stdio.h>
#include "Visuals.h"
#include "Timer.h"

void RoundOne(double durition)
{
    clearConsole();
    printf(" _____                       _      \n");
    printf("|  __ \\                     | |     \n");
    printf("| |__) |___  _   _ _ __   __| |     \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |     \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |     \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  \n");
    HoldSeconds(0.4);
    clearConsole();
    printf(" _____                       _   |_|\n");
    printf("|  __ \\                     | |     \n");
    printf("| |__) |___  _   _ _ __   __| |     \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |     \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |     \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   | |\n");
    printf("|  __ \\                     | |  |_|\n");
    printf("| |__) |___  _   _ _ __   __| |     \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |     \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |     \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   | |\n");
    printf("|  __ \\                     | |  | |\n");
    printf("| |__) |___  _   _ _ __   __| |  |_|\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |     \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |     \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   | |\n");
    printf("|  __ \\                     | |  | |\n");
    printf("| |__) |___  _   _ _ __   __| |  | |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  |_|\n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |     \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _  /_ |\n");
    printf("|  __ \\                     | |  | |\n");
    printf("| |__) |___  _   _ _ __   __| |  | |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  | |\n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  |_|\n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   __ \n");
    printf("|  __ \\                     | | /_ |\n");
    printf("| |__) |___  _   _ _ __   __| |  | |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  | |\n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  | |\n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  |_|\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   __ \n");
    printf("|  __ \\                     | | /_ |\n");
    printf("| |__) |___  _   _ _ __   __| |  | |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  | |\n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  | |\n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  |_|\n");
    HoldSeconds(1.5);////
    clearConsole();
    printf(" _____                       _   __ \n");
    printf("|  __ \\                     | | /_ |\n");
    printf("| |__) |___  _   _ _ __   __| |  | |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  | |\n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  | |\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   __ \n");
    printf("|  __ \\                     | | /_ |\n");
    printf("| |__) |___  _   _ _ __   __| |  | |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  | |\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   __ \n");
    printf("|  __ \\                     | | /_ |\n");
    printf("| |__) |___  _   _ _ __   __| |  | |\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   __ \n");
    printf("|  __ \\                     | | /_ |\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   __ \n");
}

void RoundTwo(double durition)
{
    clearConsole();
    printf(" _____                       _      \n");
    printf("|  __ \\                     | |     \n");
    printf("| |__) |___  _   _ _ __   __| |     \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |     \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |     \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  \n");
    HoldSeconds(0.4);
    clearConsole();
    printf(" _____                       _    \n");
    printf("|  __ \\                     | |  |\n");
    printf("| |__) |___  _   _ _ __   __| |     \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |    \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |   /\n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    _\n");
    printf("|  __ \\                     | |  |_\n");
    printf("| |__) |___  _   _ _ __   __| |     )\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |    /\n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |   / \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  |\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    __\n");
    printf("|  __ \\                     | |  |__\n");
    printf("| |__) |___  _   _ _ __   __| |     ) \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |    / \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |   / /\n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  |_\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    ___\n");
    printf("|  __ \\                     | |  |__ \n");
    printf("| |__) |___  _   _ _ __   __| |     ) |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |    / /\n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |   / /_\n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  |__\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    ___ \n");
    printf("|  __ \\                     | |  |__  \n");
    printf("| |__) |___  _   _ _ __   __| |     ) | \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |    / / \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |   / /_ \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  |___\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    ___   \n");
    printf("|  __ \\                     | |  |__  \\ \n");
    printf("| |__) |___  _   _ _ __   __| |     ) |  \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |    / /   \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |   / /_   \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  |____\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    ___     \n");
    printf("|  __ \\                     | |  |__  \\  \n");
    printf("| |__) |___  _   _ _ __   __| |     ) |    \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |    / /     \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |   / /_     \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  |____| \n");
    HoldSeconds(1.5);////
    clearConsole();
    printf(" _____                       _    ___     \n");
    printf("|  __ \\                     | |  |__  \\  \n");
    printf("| |__) |___  _   _ _ __   __| |     ) |    \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |    / /     \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |   / /_     \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    ___     \n");
    printf("|  __ \\                     | |  |__  \\  \n");
    printf("| |__) |___  _   _ _ __   __| |     ) |    \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |    / /     \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    ___     \n");
    printf("|  __ \\                     | |  |__  \\  \n");
    printf("| |__) |___  _   _ _ __   __| |     ) |    \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    ___     \n");
    printf("|  __ \\                     | |  |__  \\  \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _    ___     \n");
}

void RoundThree(double durition)
{
    clearConsole();
    printf(" _____                       _      \n");
    printf("|  __ \\                     | |     \n");
    printf("| |__) |___  _   _ _ __   __| |     \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |     \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |     \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_|  \n");
    HoldSeconds(0.4);
    clearConsole();
    printf(" _____                       _         \n");
    printf("|  __ \\                     | |       \n");
    printf("| |__) |___  _   _ _ __   __| |         \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |        \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |        \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_| ____  \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _         \n");
    printf("|  __ \\                     | |       \n");
    printf("| |__) |___  _   _ _ __   __| |         \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |        \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  ____  \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_| |___ \\ \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _         \n");
    printf("|  __ \\                     | |       \n");
    printf("| |__) |___  _   _ _ __   __| |         \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  ____  \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  |___ \\ \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_| __) |\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _         \n");
    printf("|  __ \\                     | |       \n");
    printf("| |__) |___  _   _ _ __   __| |   ____  \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  |___ \\ \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  __) |\n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_| |__ < \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _         \n");
    printf("|  __ \\                     | | ____  \n");
    printf("| |__) |___  _   _ _ __   __| |   |___ \\ \n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  __) |\n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  |__ < \n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_| ___) |\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   ____  \n");
    printf("|  __ \\                     | | |___ \\ \n");
    printf("| |__) |___  _   _ _ __   __| |   __) |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  |__ < \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  ___) |\n");
    printf("|_|  \\_\\___/ \\__,_|_| |_|\\__,_| |____/ \n");
    HoldSeconds(1.5);////
    clearConsole();
    printf(" _____                       _   ____  \n");
    printf("|  __ \\                     | | |___ \\ \n");
    printf("| |__) |___  _   _ _ __   __| |   __) |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  |__ < \n");
    printf("| | \\ \\ (_) | |_| | | | | (_| |  ___) |\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   ____  \n");
    printf("|  __ \\                     | | |___ \\ \n");
    printf("| |__) |___  _   _ _ __   __| |   __) |\n");
    printf("|  _  // _ \\| | | | '_ \\ / _` |  |__ < \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   ____  \n");
    printf("|  __ \\                     | | |___ \\ \n");
    printf("| |__) |___  _   _ _ __   __| |   __) |\n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   ____  \n");
    printf("|  __ \\                     | | |___ \\ \n");
    HoldSeconds(durition);
    clearConsole();
    printf(" _____                       _   ____  \n");
    HoldSeconds(durition);
}
#endif